### ISSUE TITLE
"# these RARs contain cracked .exe files and are not wanted on srrdb.com"

### ISSUE THREAD

**Issue by SpiralBrad** [srrDB/pyrescene#6]
(Similar sentiments to the below apply to the other 'blacklist' entries...)

For one, don't MOST scene release _games_ contain cracked .exe's?  I know for SURE you have tons of .SRRs for such releases there already.

Second, you don't want them on srrdb.com?  Great.  Handle it there, not in a toolset's code.  Don't restrict what users can do... especially not via some simple strings in a blacklist.  Handle it on the site side.

**Comment by pyrescene** [comment]
Rar files are only added for some special cases, besides proofs:

```
	# stores the main RARs of DVDR fixes
	# these RARs contain cracked .exe files and are not wanted on srrdb.com
	false_positives = rar_file_blacklist()
```

The blacklist improves the accuracy of that feature, and avoids unnecessary work for srrdb. It adds in a rar, somehting that normally would not happen. It's actually a positive feature instead of a restriction.

The idea is to have meta data backups, so one does not expect large rar files to be included. Not having that feature at all is more logical.
One can still add any rar into the srr, so it's not a user restriction. And the code is open.

It's also not a restriction on the srr files you are able to create.
